server:
  port: 8009
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
