server:
  port: 7001
spring:
  application:
    name: eureka-server-another
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7000/eureka